'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Heart, MapPin, Menu, X } from 'lucide-react'
import Image from 'next/image'
import { gallery, programme, story, wedding } from '@/lib/wedding-data'

const navItems = ['Invitation', 'The day', 'Our story', 'Gallery', 'RSVP']

function Entry({ onEnter }: { onEnter: () => void }) {
  return <main className="entry-screen"><div className="entry-copy"><p className="eyebrow">A wedding invitation</p><h1>Naomi <i>&</i> Benjamin</h1><p className="entry-date">14.09.25 · London</p><button className="text-button" onClick={onEnter}>Enter invitation <ArrowRight size={15} /></button></div><div className="entry-image"><Image src={wedding.heroImages[0]} alt="Naomi and Benjamin" fill priority sizes="50vw" /></div></main>
}

function Header({ onMenu }: { onMenu: () => void }) {
  return <header className="site-header"><a href="#top" className="brand">N<span>&</span>B</a><nav>{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replace(' ', '-')}`}>{item}</a>)}</nav><button aria-label="Open menu" className="menu-button" onClick={onMenu}><Menu size={20} /></button></header>
}

function Hero() {
  const [index, setIndex] = useState(0)
  useEffect(() => { const timer = setInterval(() => setIndex((i) => (i + 1) % wedding.heroImages.length), 6000); return () => clearInterval(timer) }, [])
  return <section className="hero" id="top"><div className="hero-image"><Image src={wedding.heroImages[index]} alt="A moment from Naomi and Benjamin's wedding" fill priority sizes="100vw" /></div><div className="hero-overlay" /><div className="hero-content"><p className="eyebrow">Together with their families</p><h1>Naomi <i>&</i><br />Benjamin</h1><p className="hero-date">{wedding.date}</p></div><div className="hero-footer"><span>Scroll to explore</span><ArrowDown size={16} /><div className="slider-controls"><button aria-label="Previous photo" onClick={() => setIndex((i) => (i + wedding.heroImages.length - 1) % wedding.heroImages.length)}><ArrowLeft size={16} /></button><span>0{index + 1} <b>/ 0{wedding.heroImages.length}</b></span><button aria-label="Next photo" onClick={() => setIndex((i) => (i + 1) % wedding.heroImages.length)}><ArrowRight size={16} /></button></div></div></section>
}

function Invitation() { return <section className="section invitation" id="invitation"><div className="section-intro"><p className="eyebrow">You are invited</p><h2>We’re getting<br /><i>married.</i></h2></div><div className="invitation-copy"><p className="lead">It would mean the world to us to have you there as we promise forever to one another.</p><p>Join us for an afternoon of good food, happy tears, and dancing under the glasshouse lights. We can’t wait to celebrate with you.</p><div className="meta-grid"><div><CalendarDays size={18} /><span>{wedding.date}</span></div><div><MapPin size={18} /><span>{wedding.venue}</span></div></div><a className="underlined-link" href="#the-day">See the day <ArrowDown size={15} /></a></div></section> }

function TheDay() { return <section className="day-section" id="the-day"><div className="section-heading"><p className="eyebrow">The day</p><h2>A little <i>timeline.</i></h2><p>Arrive as you are. Stay as long as you like.</p></div><div className="timeline">{programme.map(([time, title, place]) => <div className="timeline-row" key={time}><span className="time">{time}</span><div><h3>{title}</h3><p>{place}</p></div><Clock3 size={17} /></div>)}</div><div className="venue-note"><div><p className="eyebrow">Getting there</p><h3>The Glasshouse</h3><p className="muted">A light-filled Victorian conservatory in the heart of London.</p></div><a className="circle-link" href="https://maps.google.com" target="_blank" rel="noreferrer" aria-label="Open venue map"><ArrowRight size={19} /></a></div></section> }

function Story() { return <section className="section story-section" id="our-story"><div className="story-image"><Image src={wedding.gallery[4].src} alt="Naomi and Benjamin walking together" fill sizes="(max-width: 768px) 100vw, 42vw" /></div><div className="story-content"><p className="eyebrow">Our story</p><h2>It started with<br /><i>a missed train.</i></h2><div className="story-list">{story.map((item) => <div className="story-item" key={item.year}><span>{item.year}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></div>)}</div></div></section> }

function Gallery() { const [filter, setFilter] = useState('all'); const [selected, setSelected] = useState<number | null>(null); const filtered = useMemo(() => filter === 'all' ? gallery : gallery.filter((image) => image.category === filter), [filter]); return <section className="gallery-section" id="gallery"><div className="section-heading"><p className="eyebrow">A few frames</p><h2>In good <i>company.</i></h2></div><div className="filters">{['all', 'couple', 'day', 'details'].map((item) => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="gallery-grid">{filtered.map((image, i) => <button className="gallery-item" key={image.src} onClick={() => setSelected(i)}><Image src={image.src} alt={image.label} fill sizes="(max-width: 768px) 50vw, 25vw" /></button>)}</div>{selected !== null && <div className="lightbox" role="dialog" aria-modal="true" onClick={() => setSelected(null)}><button className="close-button" aria-label="Close gallery" onClick={() => setSelected(null)}><X /></button><Image src={filtered[selected].src} alt={filtered[selected].label} width={1400} height={1000} onClick={(e) => e.stopPropagation()} /></div>}</section> }

function RSVP() { const [sent, setSent] = useState(false); const [name, setName] = useState(''); return <section className="rsvp-section" id="rsvp">{sent ? <div className="success"><Check size={28} /><p className="eyebrow">Thank you, {name || 'friend'}</p><h2>We’ll see you<br /><i>in September.</i></h2><p>Your response has been noted. We can’t wait to celebrate together.</p></div> : <div className="rsvp-inner"><div><p className="eyebrow">Kindly reply</p><h2>Will you<br /><i>join us?</i></h2><p className="muted">Please let us know by 01 August 2025.</p></div><form onSubmit={(e) => { e.preventDefault(); if (name.trim()) setSent(true) }}><label>Your name<input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" /></label><label>Will you be joining us?<select defaultValue="yes"><option value="yes">Joyfully accepts</option><option value="no">Regretfully declines</option></select></label><label>Anything we should know? <textarea rows={3} placeholder="Dietary requirements, song requests..." /></label><button className="dark-button" type="submit">Send RSVP <ArrowRight size={16} /></button></form></div>}</section> }

function MobileMenu({ close }: { close: () => void }) { return <div className="mobile-menu"><button aria-label="Close menu" onClick={close}><X /></button>{navItems.map((item) => <a key={item} onClick={close} href={`#${item.toLowerCase().replace(' ', '-')}`}>{item}</a>)}</div> }

export default function Page() { const [entered, setEntered] = useState(false); const [menu, setMenu] = useState(false); if (!entered) return <Entry onEnter={() => setEntered(true)} />; return <><Header onMenu={() => setMenu(true)} />{menu && <MobileMenu close={() => setMenu(false)} />}<main><Hero /><Invitation /><TheDay /><Story /><Gallery /><RSVP /><footer><Heart size={17} fill="currentColor" /><p>With love, Naomi & Benjamin</p><a href="#top">Back to top <ChevronDown size={15} /></a></footer></main></> }
